# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '2c2d8867-20a8-49b9-82a4-2f3bd02b3cc7'
  imageRepository: 'carrentalwebsite'
  containerRegistry: 'rentalcontainer.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/dockerfile'
  tag: '$(Build.BuildId),latest'

pool:
 name: 'rental'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'Docker Registry service connection'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: '$(tag)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/k8s/manifest'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/$(ARTIFACT_NAME)'
        CleanTargetFolder: true
        OverWrite: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
