apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rental-ingress
spec:
  rules:
  - host: rental.example.com
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: rental-service
            port:
              number: 80
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: rental-service
            port:
              number: 81
      - path: /v3
        pathType: Prefix
        backend:
          service:
            name: rental-service
            port:
              number: 82
