apiVersion: v1
kind: Service
metadata:
  name: rental-service
spec:
  selector:
    app: rental
  ports:
    - protocol: TCP
      port: 80        # The internal service port
      targetPort: 8080 # The port your application is listening on
      nodePort: 30001  # The port exposed externally on all nodes
  type: NodePort  # Exposes the service on a static port on each node
