apiVersion: v1
kind: Service
metadata:
  name: rental-service-port1
spec:
  selector:
    app: rental
  ports:
    - protocol: TCP
      port: 80        # The internal service port
      targetPort: 8080 # The port your application is listening on
  type: NodePort  # Kubernetes will automatically allocate a nodePort in the valid range
