apiVersion: v1
kind: Service
metadata:
  name: rental-service
spec:
  selector:
    app: rental
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Exposes the service to the internet if supported by cloud provider